//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class eUpgrade_Company
    {
        public string PropertyCode { get; set; }
        public string CompanyName { get; set; }
        public string DotNetConnString_eUpgrade { get; set; }
        public string DomainName_eUpgrade { get; set; }
        public bool Active { get; set; }
        public string MasterPropertyCode { get; set; }
    }
}
