//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.Data.Repository.eConcierge.Interface
{
    using System;
    using System.Collections.Generic;
    using Cendyn.eConcierge.EntityModel;
    using RepositoryT.Infrastructure;
    
    
    public  partial interface IEUpgradeInventoryRepository : IRepository<eUpgradeInventory>
    {
    }
}
