//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConciergeLogin
    {
        public int ID { get; set; }
        public string ConciergeID { get; set; }
        public string password { get; set; }
        public string HOTEL_CODE { get; set; }
        public string password1 { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public bool Active { get; set; }
        public bool ReqstEmailFlg { get; set; }
    }
}
