//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyConvert
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Symbol { get; set; }
        public decimal USD_to_Rate { get; set; }
        public string CurrencyName { get; set; }
        public string EncodedSymbol { get; set; }
        public string Hotel_Code { get; set; }
    }
}
