//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DicBrand
    {
        public int ID { get; set; }
        public string BrandCode { get; set; }
        public string BrandName { get; set; }
        public int ChainID { get; set; }
        public short SortOrder { get; set; }
        public bool Active { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual DicChain DicChain { get; set; }
    }
}
