//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        public int ID { get; set; }
        public string Hotel_Code { get; set; }
        public int languageID { get; set; }
        public bool ShowWeatherYN { get; set; }
        public bool ShowRequestYN { get; set; }
        public string ConciergeName { get; set; }
        public bool HasMultiCancelPolicy { get; set; }
        public string TemplateCode { get; set; }
        public string TemplateName { get; set; }
        public string Template { get; set; }
        public string eMailType { get; set; }
        public bool HtmlYN { get; set; }
        public string Comment { get; set; }
        public bool ActiveYN { get; set; }
        public Nullable<System.DateTime> insertDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    }
}
