//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eUpgradeTransactionCode
    {
        public int ID { get; set; }
        public Nullable<int> CendynPropertyID { get; set; }
        public string HotelCode { get; set; }
        public string UpgradeType { get; set; }
        public bool PerNightCharge { get; set; }
        public string TransactionCode { get; set; }
        public bool ActiveYN { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpgradeTypeDisplayName { get; set; }
        public string PackageCode { get; set; }
    }
}
