//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eUpgradeBrandCssMapping
    {
        public int ID { get; set; }
        public string BrandCode { get; set; }
        public string BrandCss { get; set; }
        public string HotelCode { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string InsertBy { get; set; }
        public string UpdateBy { get; set; }
    }
}
