//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eUpgradeRequest
    {
        public int ID { get; set; }
        public string loginConfirmationNum { get; set; }
        public string HotelCode { get; set; }
        public string BookedRoomType { get; set; }
        public string UpgradeRoomType { get; set; }
        public Nullable<decimal> UpgradeCost { get; set; }
        public string UpgradeStatus { get; set; }
        public string DecisionPerson { get; set; }
        public Nullable<System.DateTime> OXIDateSent { get; set; }
        public string OXIMessageID { get; set; }
        public Nullable<bool> OXIDirty { get; set; }
        public string OXITransactioncode { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string TransactionCode { get; set; }
        public string UpgradeType { get; set; }
        public Nullable<bool> PerNightCharge { get; set; }
        public string OXIStatus { get; set; }
        public Nullable<System.DateTime> OXIReceiptDate { get; set; }
        public string OXIComment { get; set; }
        public decimal TotalUpgradeFees { get; set; }
        public string RequestID { get; set; }
        public string PackageCode { get; set; }
    }
}
