//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDesc
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> prePublishID { get; set; }
        public int LanguageID { get; set; }
        public Nullable<int> ParentLevelID { get; set; }
        public string Hotel_Code { get; set; }
        public string EventCategory { get; set; }
        public string EventName { get; set; }
        public string EventDescription { get; set; }
        public string Address { get; set; }
        public string Yardage { get; set; }
        public string Hours { get; set; }
        public string Image { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> DisplayPriceYN { get; set; }
        public Nullable<bool> ReservationYN { get; set; }
        public string CancellationTerm { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> ActiveYN { get; set; }
        public bool ContentNo { get; set; }
        public Nullable<System.DateTime> insertDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<bool> RevenuePP { get; set; }
        public Nullable<bool> seasonal { get; set; }
        public Nullable<int> EventGroupId { get; set; }
        public Nullable<int> OTRestaurantID { get; set; }
        public bool IsOpenTable { get; set; }
        public bool IsTitle { get; set; }
        public string Duration { get; set; }
        public bool HasQuantity { get; set; }
    }
}
