//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestPlanner_Log
    {
        public int LogID { get; set; }
        public int GuestPlannerID { get; set; }
        public string RequestID { get; set; }
        public string ConfirmationNum { get; set; }
        public string LoginConfirmationNum { get; set; }
        public string Hotel_Code { get; set; }
        public string Event { get; set; }
        public string Description { get; set; }
        public string DescID { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string EventTime { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumberPeople { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> RequestTypeID { get; set; }
        public string Other1 { get; set; }
        public string Other2 { get; set; }
        public string Status { get; set; }
        public bool ConfirmStatus { get; set; }
        public string NewConfirmStatus { get; set; }
        public string ConfirmConcierge { get; set; }
        public string ConciergeInitial { get; set; }
        public bool Removed { get; set; }
        public string ShowItinerary { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string AdditionalInfo { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> USDPrice { get; set; }
        public Nullable<bool> RevenuePP { get; set; }
        public Nullable<System.Guid> RequestSessionID { get; set; }
        public string LangId { get; set; }
        public Nullable<bool> SMSNotification { get; set; }
        public Nullable<decimal> USDGratuity { get; set; }
        public string SMSNotifyCell { get; set; }
        public Nullable<System.DateTime> LastConfirmEmailSentDate { get; set; }
    }
}
