//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelSetting
    {
        public int ID { get; set; }
        public string Hotel_Code { get; set; }
        public string LangId { get; set; }
        public Nullable<int> languageId { get; set; }
        public string SettingKey { get; set; }
        public string settingValue { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Comments { get; set; }
    }
}
