//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelSocialMedia
    {
        public int ID { get; set; }
        public string Hotel_Code { get; set; }
        public string SocialMediaType { get; set; }
        public string SocialMediaUrl { get; set; }
        public string IconUrl { get; set; }
        public string SocialMediaPosition { get; set; }
        public bool Active { get; set; }
        public short DisplayOrder { get; set; }
    }
}
