//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public int LanguageID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<bool> RTL { get; set; }
        public Nullable<bool> CommonLang { get; set; }
        public string ISO { get; set; }
        public string ImgFolder { get; set; }
        public string ExternalLanguageId { get; set; }
        public string DicLanguageId { get; set; }
        public string DicLanguageName { get; set; }
        public bool Active { get; set; }
    }
}
