//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlannerEvent
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> prePublishID { get; set; }
        public int languageID { get; set; }
        public string Hotel_Code { get; set; }
        public Nullable<int> EventDescID { get; set; }
        public string EventDetailDesc { get; set; }
        public string EventCategory { get; set; }
        public string PriceDesc { get; set; }
        public string PriceDetail { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> DisplayPriceYN { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> SortOrder2 { get; set; }
        public bool ShowOnYN { get; set; }
        public string TimeStart { get; set; }
        public string TimeEnd { get; set; }
        public Nullable<short> TimeInterval { get; set; }
        public Nullable<short> TimeDisplayType { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public bool ActiveYN { get; set; }
        public bool Seasonal { get; set; }
        public bool reservationYN { get; set; }
        public bool ContentYN { get; set; }
        public bool DropDownYN { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> RequestTypeID { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<decimal> USDPrice { get; set; }
        public Nullable<bool> RevenuePP { get; set; }
        public Nullable<int> EventGroupId { get; set; }
        public string RoomTypeCodeBooked { get; set; }
        public string RoomTypeCodeUpgrade { get; set; }
        public string UpgradeWeekDayWeekEnd { get; set; }
        public string UpgradePricedBy { get; set; }
        public string RateTypeBooked { get; set; }
        public Nullable<int> Groupid { get; set; }
    }
}
