//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateTypeLog
    {
        public int LogID { get; set; }
        public string RateTypeCode { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string ConciergeID { get; set; }
    }
}
