//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomImage
    {
        public int ID { get; set; }
        public string HotelCode { get; set; }
        public string RoomCode { get; set; }
        public string FileName { get; set; }
        public string ImageCaption { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
