//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentEmailLog
    {
        public int ID { get; set; }
        public string LoginConfirmationNum { get; set; }
        public System.DateTime SentDate { get; set; }
        public string Category { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string GroupPKG { get; set; }
        public string Source { get; set; }
        public string SendStatus { get; set; }
        public string Hotel_Code { get; set; }
        public string EmailTo { get; set; }
        public string BccEmails { get; set; }
    }
}
