//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cendyn.eConcierge.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSOProduct
    {
        public int ID { get; set; }
        public string SSOProduct1 { get; set; }
        public string SSOProductURL { get; set; }
        public string SSODisplayName { get; set; }
        public string SSOProductDesc { get; set; }
        public bool ActiveStatus { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public int SortOrder { get; set; }
    }
}
